version: '3.9'

services:
  proxy:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./frontend/dist:/

    
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgsqldb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=aqms
      - POSTGRES_USER=aqms
      - POSTGRES_DB=aqms
    networks:
      - aqms

  mongodb:
    image: mongo:4.2.3-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=aqms
      - MONGO_INITDB_ROOT_USERNAME=aqms
      - MONGO_INITDB_ROOT_PASSWORD=aqms
    volumes:
      # seeding scripts
      # - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - aqms

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "aqms"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "aqms"
      ME_CONFIG_MONGODB_URL: mongodb://aqms:aqms@mongodb:27017/
    networks:
      - aqms

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
  pgsqldb:

networks:
  aqms:
    driver: bridge